# 头部导航 Header
menu:
  首页: /
  归档: /archives
  关于: /about
rss: /atom.xml

# footer底部显示联系邮箱（在博客配置文件下添加email配置也是一样的效果）
email: 'zhouytforever@gmail.com'

# 内容 Content
excerpt_link: 继续阅读全文 »
fancybox: true

# 启用social widgets时有效
# 社交widget文本字体，不填写则不显示title
social_title: Follow me
# Social links 社交链接
social:
  github: https://github.com/zhouytforever
  weibo: http://weibo.com/zhouytforever
  zhihu: https://www.zhihu.com/people/choyt/
  email: 'zhouytforever@gmail.com'



# 侧边栏 Sidebar，目前仅支持right
sidebar: right
# 目录展示位置，有两种选择，post为文章内部右侧；widget为sidebar形式展示，在markdown文件中通过toc:false可以指定某文章不展示目录
content_position: widget
# true目录将会浮动固定位置，false则相反，当且仅当content_position=widget时该设置值有效
content_display_fixed: true
widgets:
- social
- post_content
- category
- tagcloud
- recent_posts
- lastest_comments
- hot_comment_posts
- archive

# 提供以下 7 个内置组件
# - post_content      # 文章目录
# - category          # 归类
# - tag               # 标签
# - tagcloud          # 云标签
# - archives          # 归档
# - recent_posts      # 最新文章
# - lastest_comments  # 最新评论
# - hot_comment_posts # 热评文章

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
# 分类是否显示文章数量
show_count: true

# 标签云TagClound
# 如果启动，则标签云颜色为随机
tagcloud_color: false 


# 其他参数
google_analytics:
favicon: /favicon.png
# 若使用多说，此处填写的是多说评论账号ID
# 若使用Disqus，请在博客 config 文件中填写disqus_shortname，并设置duosuo: false关闭多说评论
duoshuo_shortname: zhouytforever 
google_plus:
fb_admins:
fb_app_id:
